-- "The Office" themed sample database for squix.
-- Created by `squix example`.

PRAGMA foreign_keys = ON;

-- Departments
CREATE TABLE departments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    location TEXT NOT NULL,
    budget REAL,
    head_count INTEGER,
    metadata TEXT,
    config TEXT
);

-- Employees (many columns for overflow/scroll testing)
CREATE TABLE employees (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    position TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    date_of_birth TEXT,
    hire_date TEXT NOT NULL,
    salary REAL,
    office_number TEXT,
    department_id INTEGER,
    reports_to INTEGER,
    status TEXT,
    favorite_snack TEXT,
    hobby TEXT,
    car TEXT,
    favorite_catchphrase TEXT,
    linkedin_profile TEXT,
    skills TEXT,
    performance_rating REAL,
    bio TEXT,
    preferences TEXT,
    FOREIGN KEY (department_id) REFERENCES departments(id),
    FOREIGN KEY (reports_to) REFERENCES employees(id)
);

-- Timesheets
CREATE TABLE timesheets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_id INTEGER,
    task_name TEXT NOT NULL,
    date_worked TEXT NOT NULL,
    hours_worked REAL NOT NULL,
    description TEXT,
    billable INTEGER DEFAULT 1,
    tags TEXT,
    FOREIGN KEY (employee_id) REFERENCES employees(id)
);

-- Departments
INSERT INTO departments (name, location, budget, head_count, metadata) VALUES ('Sales', 'Scranton', 500000.00, 15, '{"notes": "High-performing team", "expansion": true}');
INSERT INTO departments (name, location, budget, head_count, metadata) VALUES ('Accounting', 'Scranton', 300000.00, 5, '{"notes": "Strict budget controls", "expansion": false}');
INSERT INTO departments (name, location, budget, head_count, metadata) VALUES ('Human Resources', 'Scranton', 200000.00, 3, '{"notes": "Focus on employee wellness", "expansion": false}');
INSERT INTO departments (name, location, budget, head_count, metadata) VALUES ('Management', 'Scranton', 400000.00, 2, '{"notes": "Leadership and strategy", "expansion": true}');
INSERT INTO departments (name, location, budget, head_count, metadata) VALUES ('Warehouse', 'Scranton', 150000.00, 10, '{"notes": "Logistics and operations", "expansion": false}');
INSERT INTO departments (name, location, budget, head_count, metadata) VALUES ('IT Support', 'Scranton', 250000.00, 4, '{"notes": "Tech maintenance", "expansion": true}');
INSERT INTO departments (name, location, budget, head_count, metadata) VALUES ('Marketing', 'New York', 350000.00, 6, '{"notes": "Brand and outreach", "expansion": true}');
INSERT INTO departments (name, location, budget, head_count, metadata) VALUES ('Customer Service', 'Scranton', 180000.00, 5, '{"notes": "Frontline support", "expansion": false}');
INSERT INTO departments (name, location, budget, head_count, metadata) VALUES ('Corporate', 'New York', 900000.00, 12, '{"notes": "Executive leadership", "expansion": true}');
INSERT INTO departments (name, location, budget, head_count, metadata) VALUES ('Reception and Security', 'Scranton', 90000.00, 3, '{"notes": "Front desk and building security", "expansion": false}');

-- Employees
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Michael', 'Scott', 'Regional Manager', 'michael.scott@dundermifflin.com', '570-555-0100', '1964-03-15', '2001-02-15', 75000.00, '101', 4, NULL, 'Active', 'Pretzel', 'Improv', 'Sebring', 'That''s what she said!', 'https://linkedin.com/in/michaelscott', '["Leadership", "Comedy"]', 3.5);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Dwight', 'Schrute', 'Assistant to the Regional Manager', 'dwight.schrute@dundermifflin.com', '570-555-0101', '1970-01-20', '2001-03-01', 55000.00, '102', 1, 1, 'Active', 'Beet chips', 'Martial Arts', 'Trans Am', 'Fact.', 'https://linkedin.com/in/dwightschrute', '["Sales", "Farming"]', 4.8);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Jim', 'Halpert', 'Sales Representative', 'jim.halpert@dundermifflin.com', '570-555-0102', '1978-10-01', '2001-06-12', 48000.00, '103', 1, 1, 'Active', 'Jelly beans', 'Pranks', 'Subaru', 'Bears. Beets. Battlestar Galactica.', 'https://linkedin.com/in/jimhalpert', '["Sales", "Pranks"]', 4.7);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Pam', 'Beesly', 'Receptionist', 'pam.beesly@dundermifflin.com', '570-555-0103', '1979-03-25', '2001-07-15', 42000.00, '104', 4, 1, 'Active', 'Yogurt', 'Drawing', 'Toyota', 'How are you not murdered every hour?', 'https://linkedin.com/in/pambeesly', '["Art", "Reception"]', 4.2);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Angela', 'Martin', 'Head of Accounting', 'angela.martin@dundermifflin.com', '570-555-0104', '1971-06-25', '2000-10-10', 60000.00, '201', 2, 1, 'Active', 'Green apple', 'Cats', 'Hyundai', 'I will not be a participant in your prank.', 'https://linkedin.com/in/angelamartin', '["Accounting", "Cats"]', 4.9);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Oscar', 'Martinez', 'Accountant', 'oscar.martinez@dundermifflin.com', '570-555-0105', '1970-02-19', '2001-04-01', 49000.00, '202', 2, 5, 'Active', 'Trail mix', 'Crossword puzzles', 'Honda', 'Actually...', 'https://linkedin.com/in/oscarmartinez', '["Accounting", "Puzzles"]', 4.6);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Kevin', 'Malone', 'Accountant', 'kevin.malone@dundermifflin.com', '570-555-0106', '1970-06-01', '2001-08-20', 47000.00, '203', 2, 5, 'Active', 'Chocolate', 'Drums', 'SUV', 'Why waste time say lot word when few word do trick?', 'https://linkedin.com/in/kevinmalone', '["Accounting", "Music"]', 3.8);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Toby', 'Flenderson', 'HR Representative', 'toby.flenderson@dundermifflin.com', '570-555-0107', '1972-01-15', '2002-01-10', 53000.00, '301', 3, 1, 'Active', 'Granola bar', 'Running', 'Sedan', 'I need to remind you that your salary is not to scale.', 'https://linkedin.com/in/tobyflenderson', '["HR", "Running"]', 4.1);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Darryl', 'Philbin', 'Warehouse Foreman', 'darryl.philbin@dundermifflin.com', '570-555-0108', '1975-06-01', '2002-06-17', 52000.00, '401', 5, 1, 'Active', 'Jerky', 'Music', 'Pickup Truck', 'Hey, dummy!', 'https://linkedin.com/in/darrylphilbin', '["Logistics", "Music"]', 4.4);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Stanley', 'Hudson', 'Sales Representative', 'stanley.hudson@dundermifflin.com', '570-555-0109', '1958-02-19', '2001-09-15', 48500.00, '105', 1, 1, 'Active', 'Pretzel', 'Crosswords', 'Chrysler', 'Did I stutter?', 'https://linkedin.com/in/stanleyhudson', '["Sales", "Crosswords"]', 4.0);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Phyllis', 'Vance', 'Sales Representative', 'phyllis.vance@dundermifflin.com', '570-555-0110', '1955-07-10', '2001-11-01', 48200.00, '106', 1, 1, 'Active', 'Cinnamon roll', 'Knitting', 'Minivan', 'Close your mouth, sweetie.', 'https://linkedin.com/in/phyllisvance', '["Sales", "Knitting"]', 4.3);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Creed', 'Bratton', 'Quality Assurance', 'creed.bratton@dundermifflin.com', '570-555-0111', '1943-11-01', '2001-11-20', 48300.00, '107', 4, 1, 'Active', 'Mung beans', 'Guitar', 'Mystery', 'I run a small fake-ID company from the car.', 'https://linkedin.com/in/creedbratton', '["Quality", "Music"]', 3.2);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Meredith', 'Palmer', 'Supplier Relations', 'meredith.palmer@dundermifflin.com', '570-555-0112', '1960-12-10', '2002-01-22', 42100.00, '108', 4, 1, 'Active', 'Vodka', 'Bowling', 'Minivan', 'I am not ashamed of my job.', 'https://linkedin.com/in/meredithpalmer', '["Relations", "Bowling"]', 3.9);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Kelly', 'Kapoor', 'Customer Service Rep', 'kelly.kapoor@dundermifflin.com', '570-555-0113', '1980-02-05', '2005-04-04', 42000.00, '109', 8, 1, 'Active', 'Cupcakes', 'Shopping', 'Civic', 'Who says exactly what they''re thinking? What kind of game is that?', 'https://linkedin.com/in/kellykapoor', '["Service", "Shopping"]', 4.5);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Ryan', 'Howard', 'Temp', 'ryan.howard@dundermifflin.com', '570-555-0114', '1983-05-05', '2005-04-11', 41000.00, '110', 1, 1, 'Active', 'Energy drink', 'Entrepreneurship', 'Volkswagen', 'I am on a path.', 'https://linkedin.com/in/ryanhoward', '["Temp", "Entrepreneurship"]', 3.7);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Erin', 'Hannon', 'Receptionist', 'erin.hannon@dundermifflin.com', '570-555-0115', '1985-05-20', '2009-09-01', 40000.00, '111', 10, 1, 'Active', 'Candy', 'Volunteering', 'Hatchback', 'I believe you.', 'https://linkedin.com/in/erinhannon', '["Reception", "Volunteering"]', 4.6);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Andy', 'Bernard', 'Sales Representative', 'andy.bernard@dundermifflin.com', '570-555-0116', '1976-03-22', '2005-09-15', 47500.00, '112', 1, 1, 'Active', 'Popcorn', 'A Cappella', 'Sedan', 'Nard Dog!', 'https://linkedin.com/in/andybernard', '["Sales", "Music"]', 4.2);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Gabe', 'Lewis', 'Corporate HR', 'gabe.lewis@dundermifflin.com', '570-555-0117', '1982-11-10', '2012-01-01', 55000.00, '302', 3, 8, 'Active', 'Soda', 'Video Games', 'SUV', 'I am not a security threat.', 'https://linkedin.com/in/gabelewis', '["HR", "Games"]', 3.5);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('David', 'Wallace', 'CFO', 'david.wallace@dundermifflin.com', '212-555-0200', '1959-08-12', '1995-05-01', 210000.00, 'NY-01', 9, NULL, 'Active', 'Pretzel', 'Sailing', 'Lexus', 'It''s a bold strategy, Cotton.', 'https://linkedin.com/in/davidwallace', '["Finance", "Leadership"]', 4.9);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Jan', 'Levinson', 'VP of Northeast Sales', 'jan.levinson@dundermifflin.com', '212-555-0201', '1966-11-30', '1998-09-14', 175000.00, 'NY-02', 9, 19, 'Inactive', 'Cottage cheese', 'Yoga', 'Sedan', 'I am going to make this my bitch.', 'https://linkedin.com/in/janlevinson', '["Sales", "Management"]', 4.0);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Holly', 'Flax', 'HR Representative', 'holly.flax@dundermifflin.com', '570-555-0202', '1974-04-18', '2008-02-25', 54000.00, '303', 3, 8, 'Active', 'String cheese', 'Comedy', 'Sedan', 'That was a joke.', 'https://linkedin.com/in/hollyflax', '["HR", "Comedy"]', 4.7);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Todd', 'Packer', 'Traveling Salesman', 'todd.packer@dundermifflin.com', '919-555-0203', '1965-07-04', '1999-03-19', 58000.00, 'Remote', 1, 1, 'Active', 'Beef jerky', 'Golf', 'Convertible', 'What''s up, my nerds?', 'https://linkedin.com/in/toddpacker', '["Sales", "Travel"]', 2.9);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Roy', 'Anderson', 'Warehouse Worker', 'roy.anderson@dundermifflin.com', '570-555-0204', '1977-02-28', '2001-04-02', 36000.00, '402', 5, 9, 'Active', 'Hot pockets', 'Watching TV', 'Truck', 'I''m just sayin''.', 'https://linkedin.com/in/royanderson', '["Warehouse", "Logistics"]', 3.4);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Nate', 'Nickerson', 'Warehouse Handyman', 'nate.nickerson@dundermifflin.com', '570-555-0205', '1955-09-09', '2003-11-11', 34000.00, '403', 5, 9, 'Active', 'Sunflower seeds', 'Birdwatching', 'Bicycle', 'I''m hard of hearing in one ear.', 'https://linkedin.com/in/natenickerson', '["Warehouse", "Maintenance"]', 3.6);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Hank', 'Doyle', 'Security Guard', 'hank.doyle@dundermifflin.com', '570-555-0206', '1949-12-02', '1996-06-30', 38000.00, 'Lobby', 10, 1, 'Active', 'Donuts', 'Naps', 'None', 'Toby? No, Toby''s gone.', 'https://linkedin.com/in/hankdoyle', '["Security", "Vigilance"]', 3.3);
INSERT INTO employees (first_name, last_name, position, email, phone, date_of_birth, hire_date, salary, office_number, department_id, reports_to, status, favorite_snack, hobby, car, favorite_catchphrase, linkedin_profile, skills, performance_rating) VALUES ('Bob', 'Vance', 'Refrigeration Specialist', 'bob.vance@vancerefrigeration.com', '570-555-0207', '1972-05-22', '2000-01-15', 62000.00, 'Basement', 5, 9, 'Active', 'Beef sticks', 'Cycling', 'Van', 'Bob Vance, Vance Refrigeration.', 'https://linkedin.com/in/bobvance', '["Refrigeration", "HVAC"]', 4.3);

-- Timesheets
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (1, 'Team Meeting', '2023-10-01', 2.0, 'Discussed sales targets', 1, '["meeting", "sales"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (2, 'Client Call', '2023-10-02', 1.5, 'Follow-up with Dwight Farms', 1, '["sales", "client"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (3, 'Prank Planning', '2023-10-03', 0.5, 'Ideas for office fun', 0, '["fun", "team"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (5, 'Budget Review', '2023-10-04', 3.0, 'Analyzed quarterly expenses', 1, '["accounting", "budget"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (3, 'Sales Calls', '2023-10-05', 5.5, 'Cold calls to prospective clients in Lackawanna County', 1, '["sales", "calls"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (2, 'Beet Harvest Logistics', '2023-10-06', 4.0, 'Coordinated Schrute Farms delivery schedule', 1, '["sales", "logistics"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (4, 'Reception Duties', '2023-10-09', 7.0, 'Answered phones, sorted mail, transferred calls', 1, '["reception", "admin"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (6, 'Quarterly Audit', '2023-10-10', 6.0, 'Reconciled accounts payable for Q3', 1, '["accounting", "audit"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (7, 'Data Entry', '2023-10-11', 3.5, 'Entered vendor invoices into the system', 1, '["accounting", "data"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (9, 'Warehouse Inventory', '2023-10-12', 8.0, 'Counted pallets and organized the loading bay', 1, '["warehouse", "inventory"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (8, 'Safety Training', '2023-10-13', 2.0, 'Conducted quarterly safety briefing', 0, '["hr", "training"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (11, 'Client Luncheon', '2023-10-15', 2.5, 'Hosted Blue Cross sales lunch', 1, '["sales", "client"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (17, 'A Cappella Warm-up', '2023-10-16', 1.0, 'Here Comes Treble vocal exercises', 0, '["music", "team"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (19, 'Board Meeting', '2023-10-17', 4.0, 'Presented Q3 earnings to the board', 1, '["corporate", "finance"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (21, 'Compliance Review', '2023-10-18', 3.0, 'Reviewed workplace harassment policies', 1, '["hr", "compliance"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (23, 'Loading Trucks', '2023-10-19', 7.5, 'Loaded outbound paper shipments', 1, '["warehouse", "shipping"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (26, 'Chiller Maintenance', '2023-10-20', 5.0, 'Serviced basement refrigeration units', 1, '["refrigeration", "maintenance"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (1, 'Conference Planning', '2023-10-22', 3.0, 'Organized the Utica brunch motivational seminar', 0, '["events", "planning"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (10, 'Pretzel Day', '2023-10-23', 1.0, 'Enjoyed the annual free soft pretzel', 0, '["pretzel", "joy"]');
INSERT INTO timesheets (employee_id, task_name, date_worked, hours_worked, description, billable, tags) VALUES (22, 'Vendor Negotiation', '2023-10-24', 2.5, 'Negotiated paper supplier contract', 1, '["sales", "negotiation"]');

-- Long prose bios
UPDATE employees SET bio = 'Michael Gary Scott is the regional manager of the Dunder Mifflin Scranton branch, a position he has held with great enthusiasm and questionable judgment since the early 2000s. Known for his catchphrases, improv comedy background, and an unwavering belief that he is the world''s best boss, Michael leads his team through a chaotic blend of heart, humor, and the occasional inappropriate comment. When he is not planning the next office party or filming his action movie Threat Level Midnight, he can be found mentoring employees he affectionately considers his family.' WHERE id = 1;
UPDATE employees SET bio = 'Dwight Kurt Schrute III is the ambitious and fiercely loyal Assistant to the Regional Manager at Dunder Mifflin Scranton, though he would much prefer the title of Assistant Regional Manager. A beet farmer by trade and a martial artist by passion, Dwight runs Schrute Farms, a working agrotourism destination famous for its table-making workshops and eccentric bed and breakfast. His rivalry with coworker Jim Halpert is the stuff of legend, as is his encyclopedic knowledge of bears, beets, and Battlestar Galactica.' WHERE id = 2;
UPDATE employees SET bio = 'James Duncan Halpert is a sales representative whose deadpan wit and effortless charm make him the office''s resident prankster and voice of reason. Though he started as a temp with dreams of something bigger, Jim found his stride at Dunder Mifflin and, more importantly, found Pam, the receptionist who became his wife. Whether he is orchestrating an elaborate prank on Dwight or simply looking into the camera for validation, Jim keeps the Scranton branch grounded in sanity.' WHERE id = 3;
UPDATE employees SET bio = 'Pamela Morgan Beesly began her career answering phones at the Dunder Mifflin front desk, but she is far more than the office receptionist. An aspiring artist with a quiet strength and a sharp sense of humor, Pam gradually grew into a confident office administrator and designer, organizing parties, painting murals, and eventually pursuing her creative dreams in Philadelphia. Her romance with Jim is the emotional heart of the office, proof that sometimes the best stories start across a cluttered desk.' WHERE id = 4;
UPDATE employees SET bio = 'Kevin Malone is the lovable, perpetually confused accountant whose simple exterior hides a genuine talent for numbers and a surprising gift for music. A drummer in his own band, Kevin approaches both spreadsheets and chili preparation with unbridled enthusiasm and a relaxed sense of urgency. He may waste time saying a lot of words when few words do the trick, but he is a beloved fixture of the Scranton branch.' WHERE id = 7;
UPDATE employees SET bio = 'Stanley Hudson is the office''s most devoted pretzel enthusiast and a man who firmly believes that the workday begins and ends exactly when it is scheduled to, no more and no less. A senior sales representative, Stanley tolerates the chaos of the Scranton branch with stoic patience, reserving his rare bursts of energy for Pretzel Day and his escape to Florida each winter. Do not disturb him during lunch, and whatever you do, never make him repeat himself.' WHERE id = 10;
UPDATE employees SET bio = 'David Wallace is the Chief Financial Officer of Dunder Mifflin and the corporate executive to whom the Scranton branch reports. A polished, thoughtful leader who genuinely tries to do right by the company, David is repeatedly tested by Michael''s antics, corporate machinations, and the slow decline of the paper industry. When the pressure of corporate life becomes too much, he retreats to his lake house to sail and work on his doomed novelty toy, Suck It.' WHERE id = 19;
UPDATE employees SET bio = 'Holly Parallax Flax is the HR representative who transferred to Scranton and quickly became Michael''s soulmate, matching his awkward humor beat for beat. Kind, quirky, and unflappably earnest, Holly brought a warmth to the office that even Toby could not manage. Her romance with Michael is one of the few storylines in which the Scranton branch gets a genuinely happy ending.' WHERE id = 21;

-- Large minified JSON blobs
UPDATE employees SET preferences = '{"profile":{"display_name":"Michael Scarn","title":"Regional Manager","timezone":"America/New_York","locale":"en-US"},"notifications":{"email":true,"sms":false,"push":{"enabled":true,"triggers":["mentions","party_invites","awards","reviews"]}},"workspace":{"theme":"dark","layout":"comfortable","sidebar_collapsed":false},"direct_reports":[2,3,4,8,9,10,11,12,13,14,15,16,17],"permissions":{"can_hire":true,"can_fire":true,"max_approval_amount":5000,"expense_categories":["travel","meals","office_supplies","party"]},"favorites":{"movie":"Threat Level Midnight","actor":"James Bond","food":"Kevin''s chili","holiday":"Valentine''s Day"},"session_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ik1pY2hhZWwgU2NvdHQiLCJpYXQiOjE2MjM0NTY3ODksImV4cCI6OTk5OTk5OTk5OSwicm9sZSI6Im1hbmFnZXIiLCJicmFuY2giOiJTY3JhbnRvbiJ9.s2vB9mKp1xQ7nZ4tH8cA0eF3dL5rU7yW9jY2bN6mQ1k"}' WHERE id = 1;
UPDATE employees SET preferences = '{"profile":{"display_name":"Dwight K. Schrute","title":"Assistant to the Regional Manager","timezone":"America/New_York","locale":"en-US","farm":"Schrute Farms"},"notifications":{"email":true,"sms":true,"push":{"enabled":true,"triggers":["beet_prices","battlestar_galactica","bear_sightings"]}},"security":{"clearance_level":"Assistant","weapons_certified":["nunchaku","pepper_spray","stun_gun"],"surveillance_enabled":true},"bed_and_breakfast":{"rooms":["America","Ireland","Germany"],"amenities":["irrigation","beet_tour","tablemaking"],"rating":4.8},"favorites":{"weapon":"pepper_spray","show":"Battlestar Galactica","animal":"bear","vegetable":"beet"}}' WHERE id = 2;
UPDATE employees SET preferences = '{"profile":{"display_name":"Jim Halpert","title":"Sales Representative","timezone":"America/New_York"},"pranks":{"total_executed":247,"targets":["Dwight","Andy","Kevin"],"greatest_hits":["vampire","gaydar","stuffing_phones_in_ceiling"],"risk_level":"medium"},"sales":{"quota":50000,"current":48200,"clients":["Staples","Lackawanna_County","Blue Cross"],"commission_rate":0.08},"sports":{"teams":["Phillies","Eagles","76ers"],"position":"small_forward"}}' WHERE id = 3;
UPDATE employees SET preferences = '{"profile":{"display_name":"Pam Beesly","title":"Receptionist / Office Administrator","timezone":"America/New_York"},"art":{"medium":"watercolor","classes":["Pratt","NYU"],"exhibitions":["First Thursdays","Emerging Artist 2009"],"style":"abstract"},"party_planning":{"role":"co_chair","events":["birthday","farewell","awards"],"budget_per_event":200},"family":{"spouse":"Jim","child":"Cece","pet":{"type":"cat","name":"Bandit"}}}' WHERE id = 4;

-- Large department config JSON blobs
UPDATE departments SET config = '{"targets":{"quarterly_revenue":1500000,"monthly_leads":240,"conversion_rate":0.22},"team_lead":"Dwight Schrute","regions":[{"name":"Northeast","rep":"Stanley","accounts":42},{"name":"Mid-Atlantic","rep":"Phyllis","accounts":38},{"name":"Local","rep":"Andy","accounts":27}],"pipeline_stages":["lead","qualified","proposal","negotiation","closed_won","closed_lost"],"integrations":{"crm":"Salesforce","calendar":"Outlook","phone":"RingCentral"},"kpi":{"calls_per_day":50,"emails_per_day":80,"meetings_per_week":12}}' WHERE id = 1;
UPDATE departments SET config = '{"fiscal_year":2024,"budget":300000,"spend_to_date":184250,"categories":[{"name":"salaries","budget":220000,"spent":148000},{"name":"supplies","budget":30000,"spent":22100},{"name":"software","budget":50000,"spent":14150}],"approvals":{"threshold_tier1":500,"threshold_tier2":5000,"threshold_tier3":50000},"reconciliation":{"status":"current","last_closed":"2024-09-30","anomalies":[]},"software":"QuickBooks"}' WHERE id = 2;
